auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

suburl:/blog
title: juzipi
url: http://juzipi.github.io/blog/
feed: /atom.xml
author_info: <a href="http://juzipi.github.io/blog/">juzipi</a>
